CREATE OR REPLACE FUNCTION public.read_quote_candidate_projection(p_user_id bigint, p_allocation_public_id uuid, p_collection_id bigint, p_rarity_code text)
RETURNS TABLE (inventory_item_id bigint, inventory_item_public_id uuid, sku_id bigint, sku_public_id uuid, catalog_item_id bigint, collection_id bigint, rarity_code text, canonical_float numeric, valuation_snapshot_item_id bigint, verified_price_microcredits bigint, warehouse_available_units integer, warehouse_reserved_units integer, sku_liability_microcredits bigint, sku_reserved_units integer, collection_liability_microcredits bigint, scarcity_weight_numerator bigint, scarcity_weight_denominator bigint)
LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp AS $function$
 SELECT inventory.id, inventory.public_id, sku.id, sku.public_id, catalog.id, catalog.collection_id, catalog.rarity_code, inventory.canonical_float, valuation.snapshot_item_id, valuation.verified_price_microcredits, stock.available_units, stock.reserved_units, COALESCE(sku_risk.liability_microcredits,0), COALESCE(sku_risk.reserved_units,0), COALESCE(collection_risk.liability_microcredits,0), COALESCE(scarcity.weight_multiplier_numerator,1), COALESCE(scarcity.weight_multiplier_denominator,1)
 FROM public.seed_allocations allocation JOIN public.inventory_items inventory ON inventory.retired_at IS NULL JOIN public.inventory_positions position ON position.inventory_item_id=inventory.id AND position.in_warehouse JOIN public.skus sku ON sku.id=inventory.sku_id AND sku.enabled JOIN public.catalog_items catalog ON catalog.id=sku.catalog_item_id AND catalog.enabled AND catalog.collection_id=p_collection_id AND catalog.rarity_code=p_rarity_code JOIN public.warehouse_stock stock ON stock.sku_id=sku.id JOIN public.current_valuations valuation ON valuation.sku_id=sku.id JOIN public.risk_state risk_state ON risk_state.singleton AND valuation.snapshot_id=risk_state.valuation_snapshot_id LEFT JOIN public.risk_sku_exposures sku_risk ON sku_risk.sku_id=sku.id LEFT JOIN public.risk_collection_exposures collection_risk ON collection_risk.collection_id=catalog.collection_id LEFT JOIN public.current_collection_scarcity scarcity ON scarcity.collection_id=catalog.collection_id
 WHERE allocation.user_id=p_user_id AND allocation.public_id=p_allocation_public_id AND allocation.released_at IS NULL AND allocation.expires_at>clock_timestamp() ORDER BY inventory.id;
$function$;
REVOKE ALL ON FUNCTION public.read_quote_candidate_projection(bigint,uuid,bigint,text) FROM PUBLIC;
DO $block$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='contracter_runtime') THEN GRANT EXECUTE ON FUNCTION public.read_quote_candidate_projection(bigint,uuid,bigint,text) TO contracter_runtime; END IF; END $block$;
